#!/bin/bash
set -e

usage() {
   echo "Usage: $0 [options]"
   echo "  -h, -?         display this help screen"
}

while getopts "h?j:" arg; do
   case "$arg" in
      h|\?)
         usage
         exit 0
      ;;
      *)
         usage >&2
         exit 1
      ;;
   esac
done
shift $((OPTIND -1))

PS1="(buildenv) \u@\h:\w\$ " /bin/bash --norc
